### ISSUE TITLE
Address already in use [98] but it isn't

### ISSUE THREAD

**Issue by Scarabaea** [fiduswriter/fiduswriter#265] opened 2016-08-10 13:03 UTC
Hi,
I installed finduswriter like described but when I want to start the server up, I get this error:

August 10, 2016 - 07:48:34
Django version 1.9.7, using settings 'fiduswriter.settings'
Django tornado server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f5a75913a28>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/scarabaea/fiduswriter/base/management/commands/runserver.py", line 68, in inner_run
    run_server(self.port)
  File "/home/scarabaea/fiduswriter/base/servers/tornado_django_hybrid.py", line 48, in run
    make_tornado_server().listen(int(port))
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 196, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

I tried:
- different ports
- with and without sudo
- netstat and lsof show nothing using the port

To me it looks like the server starts up properly and then shuts down because it tries to start a second time on the same port and throws an error?

**Comment by johanneswilm** [comment] 2016-08-11 17:51
What is the exact command you use to start it? Are you following the instructions of the README 1:1?

**Comment by Scarabaea** [comment] 2016-08-11 18:32
Yes, followed 1:1.
I thought it might be a problem with my system, so I created a new basic django project and started that server. That worked perfectly fine.

I use ` ./manage.py runserver`. Tried it with and without sudo and with and without port number.
Thank you very much for your help.

**Comment by johanneswilm** [comment] 2016-08-11 18:36
Ok, so this is NOT a django server you are starting with `./manage.py runserver`. That's why I'm asking if you really followed this all 1:1 on  an Ubuntu machine (with nothing else pre-installed) exactly like the instructions ask for. Even the slightest change, or you trying to do something else that "always works with django" will likely make the entire thing crash.

You shouldn't use `sudo` (as the instructions indicate). 

I don't mean to be rude, but until now, every time I ask at least three times, it turns out they have done something apart from the standard instructions anyway, and that was the cause for it not working.

But so I understand that this is not the case for you. What version of Ubuntu are you running?

**Comment by johanneswilm** [comment] 2016-08-16 19:56
@Scarabaea DId you get any further on this? If not, what version of Ubuntu are you running?

**Comment by Scarabaea** [comment] 2016-08-16 19:59
Hi, sorry I did not investigate further.

I'm running Ubuntu 14.04.

**Comment by johanneswilm** [comment] 2016-08-16 20:01
@Scarabaea And this is vanilla ubuntu, nothing else installed? You are just trying to run this on the command line?

**Comment by johanneswilm** [comment] 2016-08-16 20:02
And the error shows right away when you try to start it?

**Comment by johanneswilm** [comment] 2016-08-16 20:05
I get that error message if I try to start the fidus writer server in two different terminals. The first one shows:

```
$ ./manage.py runserver
August 16, 2016 - 15:00:25
Django version 1.9.7, using settings 'fiduswriter.settings'
Django tornado server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

And the second shows:

```
$ ./manage.py runserverAugust 16, 2016 - 15:00:50
Django version 1.9.7, using settings 'fiduswriter.settings'
Django tornado server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7fef98bb9c80>
Traceback (most recent call last):
...
socket.error: [Errno 98] Address already in use

**Comment by Scarabaea** [comment] 2016-08-16 20:32
Yes, it shows right away. I run `./manage.py runserver` (only one terminal) and get the reported message.
Am I correct that findus uses tornado? 
I just tried running a minimal tornado example and ran into the same error. So it looks to me that this is a problem with my ubuntu installation.

**Comment by johanneswilm** [comment] 2016-08-16 20:36
@Scarabaea Yes indeed, internally it uses tornado. If you find out what is preventing tornado from running on your machine, it would be good to document this in case others run into the same problem.

**Comment by johanneswilm** [comment] 2016-08-22 22:16
I will close this issue, as it seems not to be an issue caused by Fidus Writer, but please reopen if you find out that there is something we can do about this, @Scarabaea !

**Closed** 2016-08-22 22:17 UTC
