### ISSUE TITLE
Misplaced screen elements

### ISSUE THREAD

**Issue by Anastasiakhram** [fiduswriter/fiduswriter#1177] opened 2021-08-31 15:57 UTC
Hey!
While using FidusWriter I have noticed that some screen items (icons, text) are represented incorrectly on my screen (please, see the pictures below). 
Usually I use Chrome but the errors persist also in Edge and Firefox. I am using a laptop with 15.6 inches screen and Microsoft Windows 10 Home OS version 10.0.19043.
Thank you in advance!

![2021-08-30_16-02-11 (3)](https://user-images.githubusercontent.com/89462149/131530903-65669d7e-18b8-4e07-b2bd-2c3d5c9eff43.png)
![2021-08-30_16-09-55 (2)](https://user-images.githubusercontent.com/89462149/131530912-1187e09b-3770-4a2b-8533-e6c09e35cd44.png)
![2021-08-30_18-55-38](https://user-images.githubusercontent.com/89462149/131530916-a7610172-45c9-4aac-8a1d-4600006d9b57.png)
![2021-08-25_11-49-07 (2)](https://user-images.githubusercontent.com/89462149/131536044-93fcd516-08e9-4a46-b722-e3436b968b91.png)

**Comment by johanneswilm** [comment] 2021-08-31 16:03
Hey @Anastasiakhram ,
indeed. This doesn't look right. May I ask what your screen resolution is? (how many pixels by how many pixels)? The screenshot seems to be 1922 x 950 which I don't think I have seen before. 1920 x 1080 is common though.

**Comment by johanneswilm** [comment] 2021-08-31 16:09
Another question @Anastasiakhram - I am running this with a 1920 x 1080 screen and everything looks much smaller to me. Is it possible that you have activated your browser's zoom function?

**Comment by johanneswilm** [comment] 2021-08-31 16:18
Screenshot 1: Can only reproduce if I activate zoom in my browser.

Screenshot 2 looks OK. Except that it shouldn't have a scrollbar. The dot menu is placed where it should be.

Screenshot 3: I can confirm the cutoff. This needs to be fixed.

Screenshot 4: Which email software are you using? It looks OK in Gmail.

**Comment by Anastasiakhram** [comment] 2021-09-01 11:22
> Hey @Anastasiakhram ,
> indeed. This doesn't look right. May I ask what your screen resolution is? (how many pixels by how many pixels)? The screenshot seems to be 1922 x 950 which I don't think I have seen before. 1920 x 1080 is common though.

Hey @johanneswilm , thank you for the quick response! My screen resolution is 1920 x 1080, however I have just found out that the scale was set automatically to 125%. Setting it back to 100% fixed the problem from the first screenshot, the rest stayed the same. The email issue should then be linked to the email software indeed - I am using Roundcube. Therefore I agree that only the issue with the header menu needs to be fixed:)

**Comment by johanneswilm** [comment] 2021-09-05 00:17
Hey @Anastasiakhram the issues you mention should be fixed in version 3.10.9. Please reopen this issue if it's not entirely fixed.

**Closed by johanneswilm** 2021-09-05 00:17 UTC
