### ISSUE TITLE
Problem with exporting FW-documents as docx-/ODT-files

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1256] opened 2023-09-13 11:07 UTC
There is a recurring problem in exporting FW-documents as docx-/ODT-files. The export fails silently, other formats work fine, though. It seems that this is related to comments, at least judging from the Chrome-console:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'resolved')`

A completely stripped down FW-document which after importing shows the described problem can be downloaded here: https://cloud.rz.uni-kiel.de/index.php/s/Yf6kpRBYZaoKD8J

**Comment by johanneswilm** [comment] 2023-09-13 11:12
Will tro to check and fix this within 3 days.

**Comment by johanneswilm** [comment] 2023-09-18 03:37
@nmueller18 The issue has been found and fixed for DOCX. I cannot reproduce the issue for ODT. If you could provide a full fidus file (not slim fidus), I could try to identify the issue.

**Comment by johanneswilm** [comment] 2023-10-16 10:57
Has been fixed in 3.11.15

**Closed by johanneswilm** 2023-10-16 10:57 UTC
